const iconBaseUrl = "https://skillicons.dev/icons?i=";
export const TECHNICAL_SKILLS = [
  {
    value: "JavaScript",
    label: "JavaScript",
    image: `${iconBaseUrl}js`,
    category: "frontend",
  },
  {
    value: "TypeScript",
    label: "TypeScript",
    image: `${iconBaseUrl}ts`,
    category: "frontend",
  },
  {
    value: "React",
    label: "React",
    image: `${iconBaseUrl}react`,
    category: "frontend",
  },
  {
    value: "Next.js",
    label: "Next.js",
    image: `${iconBaseUrl}nextjs`,
    category: "frontend",
  },
  {
    value: "Vue.js",
    label: "Vue.js",
    image: `${iconBaseUrl}vue`,
    category: "frontend",
  },
  {
    value: "Angular",
    label: "Angular",
    image: `${iconBaseUrl}angular`,
    category: "frontend",
  },
  {
    value: "Node.js",
    label: "Node.js",
    image: `${iconBaseUrl}nodejs`,
    category: "backend",
  },
  {
    value: "Express",
    label: "Express",
    image: `${iconBaseUrl}express`,
    category: "backend",
  },
  {
    value: "Python",
    label: "Python",
    image: `${iconBaseUrl}python`,
    category: "backend",
  },
  {
    value: "Django",
    label: "Django",
    image: `${iconBaseUrl}django`,
    category: "backend",
  },
  {
    value: "Flask",
    label: "Flask",
    image: `${iconBaseUrl}flask`,
    category: "backend",
  },
  {
    value: "Java",
    label: "Java",
    image: `${iconBaseUrl}java`,
    category: "backend",
  },
  {
    value: "Spring Boot",
    label: "Spring Boot",
    image: `${iconBaseUrl}spring`,
    category: "backend",
  },
  {
    value: "C#",
    label: "C#",
    image: `${iconBaseUrl}cs`,
    category: "backend",
  },
  {
    value: ".NET",
    label: ".NET",
    image: `${iconBaseUrl}dotnet`,
    category: "backend",
  },
  {
    value: "PHP",
    label: "PHP",
    image: `${iconBaseUrl}php`,
    category: "backend",
  },
  {
    value: "Laravel",
    label: "Laravel",
    image: `${iconBaseUrl}laravel`,
    category: "backend",
  },
  {
    value: "Ruby",
    label: "Ruby",
    image: `${iconBaseUrl}ruby`,
    category: "backend",
  },
  {
    value: "Ruby on Rails",
    label: "Ruby on Rails",
    image: `${iconBaseUrl}rails`,
    category: "backend",
  },
  {
    value: "Swift",
    label: "Swift",
    image: `${iconBaseUrl}swift`,
    category: "other",
  },
  {
    value: "Kotlin",
    label: "Kotlin",
    image: `${iconBaseUrl}kotlin`,
    category: "other",
  },
  {
    value: "Flutter",
    label: "Flutter",
    image: `${iconBaseUrl}flutter`,
    category: "other",
  },
  {
    value: "React Native",
    label: "React Native",
    image: ``,
    category: "other",
  },
  {
    value: "HTML",
    label: "HTML",
    image: `${iconBaseUrl}html`,
    category: "frontend",
  },
  {
    value: "CSS",
    label: "CSS",
    image: `${iconBaseUrl}css`,
    category: "frontend",
  },
  {
    value: "Sass",
    label: "Sass",
    image: `${iconBaseUrl}sass`,
    category: "frontend",
  },
  {
    value: "Tailwind CSS",
    label: "Tailwind CSS",
    image: `${iconBaseUrl}tailwind`,
    category: "frontend",
  },
  {
    value: "Bootstrap",
    label: "Bootstrap",
    image: `${iconBaseUrl}bootstrap`,
    category: "frontend",
  },
  {
    value: "Material UI",
    label: "Material UI",
    image: `${iconBaseUrl}materialui`,
    category: "frontend",
  },
  {
    value: "GraphQL",
    label: "GraphQL",
    image: `${iconBaseUrl}graphql`,
    category: "backend",
  },
  {
    value: "REST API",
    label: "REST API",
    image: `${iconBaseUrl}restapi`,
    category: "backend",
  },
  {
    value: "SQL",
    label: "SQL",
    image: ``,
    category: "backend",
  },
  {
    value: "PostgreSQL",
    label: "PostgreSQL",
    image: `${iconBaseUrl}postgresql`,
    category: "backend",
  },
  {
    value: "MySQL",
    label: "MySQL",
    image: `${iconBaseUrl}mysql`,
    category: "backend",
  },
  {
    value: "MongoDB",
    label: "MongoDB",
    image: `${iconBaseUrl}mongodb`,
    category: "backend",
  },
  {
    value: "Firebase",
    label: "Firebase",
    image: `${iconBaseUrl}firebase`,
    category: "backend",
  },
  { value: "AWS", label: "AWS", image: `${iconBaseUrl}aws`, category: "tool" },
  {
    value: "Azure",
    label: "Azure",
    image: `${iconBaseUrl}azure`,
    category: "tool",
  },
  {
    value: "Google Cloud",
    label: "Google Cloud",
    image: `${iconBaseUrl}gcp`,
    category: "tool",
  },
  {
    value: "Docker",
    label: "Docker",
    image: `${iconBaseUrl}docker`,
    category: "tool",
  },
  {
    value: "Kubernetes",
    label: "Kubernetes",
    image: `${iconBaseUrl}kubernetes`,
    category: "tool",
  },
  { value: "Git", label: "Git", image: `${iconBaseUrl}git`, category: "tool" },
  {
    value: "GitHub",
    label: "GitHub",
    image: `${iconBaseUrl}github`,
    category: "tool",
  },
  {
    value: "GitLab",
    label: "GitLab",
    image: `${iconBaseUrl}gitlab`,
    category: "tool",
  },
  {
    value: "CI/CD",
    label: "CI/CD",
    image: ``,
    category: "tool",
  },
  {
    value: "Jest",
    label: "Jest",
    image: `${iconBaseUrl}jest`,
    category: "tool",
  },
  {
    value: "Cypress",
    label: "Cypress",
    image: `${iconBaseUrl}cypress`,
    category: "tool",
  },
  {
    value: "Redux",
    label: "Redux",
    image: `${iconBaseUrl}redux`,
    category: "frontend",
  },
  {
    value: "Webpack",
    label: "Webpack",
    image: `${iconBaseUrl}webpack`,
    category: "tool",
  },
  {
    value: "Figma",
    label: "Figma",
    image: `${iconBaseUrl}figma`,
    category: "tool",
  },
  {
    value: "Adobe XD",
    label: "Adobe XD",
    image: `${iconBaseUrl}adobe-xd`,
    category: "tool",
  },
  {
    value: "Sketch",
    label: "Sketch",
    image: ``,
    category: "tool",
  },
  {
    value: "Redis",
    label: "Redis",
    image: `${iconBaseUrl}redis`,
    category: "backend",
  },
  {
    value: "MySQL",
    label: "MySQL",
    image: `${iconBaseUrl}mysql`,
    category: "backend",
  },
  {
    value: "PostgreSQL",
    label: "PostgreSQL",
    image: `${iconBaseUrl}postgresql`,
    category: "backend",
  },

  {
    value: "Vuetify",
    label: "Vuetify",
    image: ``,
    category: "frontend",
  },
];
