# .github/workflows/reset-limits.yml
name: Reset Limits

on:
  schedule:
    - cron: "5 0 * * *" # every day at 12:05 AM UTC

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Call reset API
        run: |
          curl -X POST "https://createfolio.app/api/reset-limits?key=${{ secrets.APPWRITE_API_KEY }}"
