// import { type Icon as LucideIcon } from "lucide-react";
import { SiGoogle, SiGithub } from "@icons-pack/react-simple-icons";
import { FaLinkedin } from "react-icons/fa";
import {
  Monitor,
  Pencil,
  Smartphone,
  Palette,
  ArrowLeft,
  ArrowLeftIcon,
  ArrowRight,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ExternalLinkIcon,
  Download,
  RocketIcon,
  Settings,
  Mail,
  Upload,
  ChevronsUpDown,
  ChevronDownIcon,
  ChevronUpIcon,
  CircleIcon,
  CheckIcon,
  SearchIcon,
  XIcon,
  ChevronRightIcon,
  AlertCircle,
  Menu,
  X,
  FolderIcon,
  CodeIcon,
  BrainIcon,
  WrenchIcon,
  Loader2,
  ExternalLink,
  Phone,
  ChevronDown,
  MailIcon,
  PhoneIcon,
  CalendarIcon,
  BriefcaseIcon,
  Copy,
  Check,
  Sun,
  Moon,
  GripVertical,
  Eye,
  EyeOff,
  Save,
  Plus,
  Trash,
  HashIcon,
  ChartBar,
  User,
  LogOut,
  File,
  FileUp,
} from "lucide-react";
// export type Icon = typeof LucideIcon;

export const Icons = {
  gitHub: SiGithub,
  spinner: Loader2,
  phone: Phone,
  google: SiGoogle,
  monitor: Monitor,
  smartphone: Smartphone,
  arrowLeft: ArrowLeft,
  arrowLeftIcon: ArrowLeftIcon,
  arrowRight: ArrowRight,
  arrowRightIcon: ArrowRightIcon,
  download: Download,
  rocketIcon: RocketIcon,
  settings: Settings,
  linkedin: FaLinkedin,
  mail: Mail,
  upload: Upload,
  chevronsUpDown: ChevronsUpDown,
  chevronDownIcon: ChevronDownIcon,
  chevronUpIcon: ChevronUpIcon,
  circleIcon: CircleIcon,
  checkIcon: CheckIcon,
  searchIcon: SearchIcon,
  xIcon: XIcon,
  chevronRightIcon: ChevronRightIcon,
  alertCircle: AlertCircle,
  menu: Menu,
  x: X,
  externalLink: ExternalLink,
  folderIcon: FolderIcon,
  codeIcon: CodeIcon,
  brainIcon: BrainIcon,
  wrenchIcon: WrenchIcon,
  phoneIcon: PhoneIcon,
  calendarIcon: CalendarIcon,
  briefcaseIcon: BriefcaseIcon,
  copy: Copy,
  check: Check,
  sun: Sun,
  moon: Moon,
  gripVertical: GripVertical,
  eye: Eye,
  eyeOff: EyeOff,
  save: Save,
  plus: Plus,
  trash: Trash,
  hashIcon: HashIcon,
  chartBar: ChartBar,
  chevronDown: ChevronDown,
  mailIcon: MailIcon,
  externalLinkIcon: ExternalLinkIcon,
  arrowUpIcon: ArrowUpIcon,
  arrowDownIcon: ArrowDownIcon,
  paletteIcon: Palette,
  pencil: Pencil,
  user: User,
  logout: LogOut,
  file: File,
  fileUpload: FileUp,
};
